{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNU/Z9E82K/fH1fMjHqMxQu",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/farazaghajani-eng/flexibility-pocket-robust-ml-/blob/main/hydro_flex.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 6,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "tPYEJPgtyVcT",
        "outputId": "bee1f979-fd88-4526-e874-8ee70d043f87"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: pulp in /usr/local/lib/python3.12/dist-packages (3.3.0)\n",
            "Status: Optimal\n",
            "Total cost = 11722.00 k$\n",
            "\n",
            "--- Investment Decisions ---\n",
            "Rehab G1: 0.0\n",
            "Rehab G2: 1.0\n",
            "Storage B1 Capacity: 0.00 MWh\n",
            "Hydrogen el Capacity: 0.00 units\n",
            "Hydrogen fc Capacity: 0.00 units\n",
            "Hydrogen store Capacity: 0.00 units\n",
            "\n",
            "--- Operational Decisions (per scenario and time step) ---\n",
            "\n",
            "Scenario: s1\n",
            "  Time Step: 0\n",
            "    Generation G1: 0.00 MW (Committed: 0.0)\n",
            "    Generation G2: 370.00 MW (Committed: 1.0)\n",
            "    Storage B1 Charge: 0.00 MW, Discharge: 0.00 MW, SOC: 0.00 MWh\n",
            "    Electrolyzer Input: 0.00 MW, Fuel Cell Output: 0.00 MW\n",
            "    H2 Storage Level: 0.00 MWh\n",
            "    Load Shedding: 0.00 MW, Wind Curtailment: 0.00 MW, Solar Curtailment: 0.00 MW\n",
            "  Time Step: 1\n",
            "    Generation G1: 50.00 MW (Committed: 1.0)\n",
            "    Generation G2: 420.00 MW (Committed: 1.0)\n",
            "    Storage B1 Charge: 0.00 MW, Discharge: 0.00 MW, SOC: 0.00 MWh\n",
            "    Electrolyzer Input: 0.00 MW, Fuel Cell Output: 0.00 MW\n",
            "    H2 Storage Level: 0.00 MWh\n",
            "    Load Shedding: 0.00 MW, Wind Curtailment: 0.00 MW, Solar Curtailment: 0.00 MW\n",
            "\n",
            "Scenario: s2\n",
            "  Time Step: 0\n",
            "    Generation G1: 50.00 MW (Committed: 1.0)\n",
            "    Generation G2: 400.00 MW (Committed: 1.0)\n",
            "    Storage B1 Charge: 0.00 MW, Discharge: 0.00 MW, SOC: 0.00 MWh\n",
            "    Electrolyzer Input: 0.00 MW, Fuel Cell Output: 0.00 MW\n",
            "    H2 Storage Level: 0.00 MWh\n",
            "    Load Shedding: 0.00 MW, Wind Curtailment: 0.00 MW, Solar Curtailment: 0.00 MW\n",
            "  Time Step: 1\n",
            "    Generation G1: 60.00 MW (Committed: 1.0)\n",
            "    Generation G2: 480.00 MW (Committed: 1.0)\n",
            "    Storage B1 Charge: 0.00 MW, Discharge: 0.00 MW, SOC: 0.00 MWh\n",
            "    Electrolyzer Input: 0.00 MW, Fuel Cell Output: 0.00 MW\n",
            "    H2 Storage Level: 0.00 MWh\n",
            "    Load Shedding: 0.00 MW, Wind Curtailment: 0.00 MW, Solar Curtailment: 0.00 MW\n"
          ]
        }
      ],
      "source": [
        "!pip install pulp\n",
        "\n",
        "import pulp as pl\n",
        "import numpy as np\n",
        "\n",
        "# ---- Small test data (replace with your IEEE 39 later) ----\n",
        "# Scenarios\n",
        "scenarios = ['s1', 's2']\n",
        "prob = {'s1': 0.6, 's2': 0.4}\n",
        "T = [0, 1]  # two time steps\n",
        "G = ['G1', 'G2']\n",
        "S = ['B1']\n",
        "H = ['el', 'fc', 'store']\n",
        "\n",
        "# Parameters\n",
        "Pmin = {'G1': 50, 'G2': 100}\n",
        "Pmax = {'G1': 250, 'G2': 400}\n",
        "RU = {'G1': 60, 'G2': 80}\n",
        "RD = {'G1': 60, 'G2': 80}\n",
        "C_var = {'G1': 15, 'G2': 12}\n",
        "C_inv_g = {'G1': 500, 'G2': 700}  # k$\n",
        "delta_P = {'G1': 50, 'G2': 80}\n",
        "delta_RU = {'G1': 20, 'G2': 30}\n",
        "C_inv_s = {'B1': 200}  # k$/MWh\n",
        "eta_ch = {'B1': 0.9}\n",
        "eta_dis = {'B1': 0.9}\n",
        "C_inv_h = {'el': 600, 'fc': 800, 'store': 10}  # k$/MW or k$/MWh\n",
        "eta_el = 0.7\n",
        "eta_fc = 0.6\n",
        "VOLL = 5000\n",
        "dt = 1\n",
        "\n",
        "# Load & renewable scenarios (MW)\n",
        "D = {(0,'s1'):500, (1,'s1'):600, (0,'s2'):550, (1,'s2'):650}\n",
        "Wind = {(0,'s1'):80, (1,'s1'):100, (0,'s2'):60, (1,'s2'):90}\n",
        "Solar = {(0,'s1'):50, (1,'s1'):30, (0,'s2'):40, (1,'s2'):20}\n",
        "R_up = {0:100, 1:150}\n",
        "R_down = {0:80, 1:120}\n",
        "\n",
        "# ---- Build model ----\n",
        "model = pl.LpProblem(\"TwoStage_Stochastic_Hydrogen\", pl.LpMinimize)\n",
        "\n",
        "# First-stage variables\n",
        "y = {g: pl.LpVariable(f\"y_{g}\", cat='Binary') for g in G}\n",
        "z = {s: pl.LpVariable(f\"z_{s}\", lowBound=0) for s in S}\n",
        "w = {h: pl.LpVariable(f\"w_{h}\", lowBound=0) for h in H}\n",
        "\n",
        "# Second-stage variables (indexed by t, scen)\n",
        "p_gen = {(g,t,scen): pl.LpVariable(f\"p_{g}_{t}_{scen}\", lowBound=0) for g in G for t in T for scen in scenarios} # Changed lowBound to 0\n",
        "u = {(g,t,scen): pl.LpVariable(f\"u_{g}_{t}_{scen}\", cat='Binary') for g in G for t in T for scen in scenarios}\n",
        "p_ch = {(s,t,scen): pl.LpVariable(f\"ch_{s}_{t}_{scen}\", lowBound=0) for s in S for t in T for scen in scenarios}\n",
        "p_dis = {(s,t,scen): pl.LpVariable(f\"dis_{s}_{t}_{scen}\", lowBound=0) for s in S for t in T for scen in scenarios}\n",
        "soc = {(s,t,scen): pl.LpVariable(f\"soc_{s}_{t}_{scen}\", lowBound=0) for s in S for t in T for scen in scenarios}\n",
        "p_el_in = {(t,scen): pl.LpVariable(f\"el_in_{t}_{scen}\", lowBound=0) for t in T for scen in scenarios}\n",
        "p_fc_out = {(t,scen): pl.LpVariable(f\"fc_out_{t}_{scen}\", lowBound=0) for t in T for scen in scenarios}\n",
        "H2_sto = {(t,scen): pl.LpVariable(f\"H2_{t}_{scen}\", lowBound=0) for t in T for scen in scenarios}\n",
        "LS = {(t,scen): pl.LpVariable(f\"LS_{t}_{scen}\", lowBound=0) for t in T for scen in scenarios}\n",
        "CW = {(t,scen): pl.LpVariable(f\"CW_{t}_{scen}\", lowBound=0) for t in T for scen in scenarios}\n",
        "CS = {(t,scen): pl.LpVariable(f\"CS_{t}_{scen}\", lowBound=0) for t in T for scen in scenarios}\n",
        "\n",
        "# Auxiliary variables for linearization of product of (expression * binary variable)\n",
        "P_max_prod = {(g,t,scen): pl.LpVariable(f\"P_max_prod_{g}_{t}_{scen}\", lowBound=0)\n",
        "              for g in G for t in T for scen in scenarios}\n",
        "\n",
        "# Objective: investment + expected operational cost\n",
        "obj_invest = pl.lpSum(C_inv_g[g]*y[g] for g in G) + pl.lpSum(C_inv_s[s]*z[s] for s in S) + pl.lpSum(C_inv_h[h]*w[h] for h in H)\n",
        "obj_op = pl.lpSum(prob[scen] * (\n",
        "    pl.lpSum(C_var[g]*p_gen[g,t,scen] for g in G for t in T) +\n",
        "    pl.lpSum(0.5*(p_ch[s,t,scen]+p_dis[s,t,scen]) for s in S for t in T) +\n",
        "    pl.lpSum(0.1*(p_el_in[t,scen]+p_fc_out[t,scen]) for t in T) +\n",
        "    pl.lpSum(VOLL*LS[t,scen] for t in T)\n",
        ") for scen in scenarios)\n",
        "model += obj_invest + obj_op\n",
        "\n",
        "# Constraints\n",
        "for scen in scenarios:\n",
        "    for t in T:\n",
        "        # Power balance\n",
        "        model += (\n",
        "            pl.lpSum(p_gen[g,t,scen] for g in G) +\n",
        "            pl.lpSum(p_dis[s,t,scen] - p_ch[s,t,scen] for s in S) +\n",
        "            (p_fc_out[t,scen] - p_el_in[t,scen]) +\n",
        "            (Wind[(t,scen)] - CW[(t,scen)]) + (Solar[(t,scen)] - CS[(t,scen)]) +\n",
        "            LS[(t,scen)] == D[(t,scen)]\n",
        "        ), f\"Power_Balance_{t}_{scen}\"\n",
        "\n",
        "        # Thermal max/min with rehab\n",
        "        for g in G:\n",
        "            # Linearization of (Pmax[g] + y[g]*delta_P[g]) * u[g,t,scen]\n",
        "            X_expr = Pmax[g] + y[g]*delta_P[g]\n",
        "            Z_var = u[g,t,scen]\n",
        "            P_prod_var = P_max_prod[(g,t,scen)]\n",
        "            M_g_capacity = Pmax[g] + delta_P[g] # A valid upper bound for X_expr\n",
        "\n",
        "            model += P_prod_var <= X_expr, f\"Linearize_Pmax_prod_1_{g}_{t}_{scen}\"\n",
        "            model += P_prod_var <= M_g_capacity * Z_var, f\"Linearize_Pmax_prod_2_{g}_{t}_{scen}\"\n",
        "            model += P_prod_var >= X_expr - M_g_capacity * (1 - Z_var), f\"Linearize_Pmax_prod_3_{g}_{t}_{scen}\"\n",
        "\n",
        "            # Apply the linearized max capacity to p_gen\n",
        "            model += p_gen[g,t,scen] <= P_prod_var, f\"Pgen_max_capacity_{g}_{t}_{scen}\"\n",
        "            # Min capacity constraint remains as it is fine (constant * binary variable)\n",
        "            model += p_gen[g,t,scen] >= Pmin[g] * u[g,t,scen], f\"Pgen_min_capacity_{g}_{t}_{scen}\"\n",
        "\n",
        "        # Reserve requirements\n",
        "        # Upward reserve uses the linearized product P_max_prod\n",
        "        model += pl.lpSum(P_max_prod[(g,t,scen)] - p_gen[g,t,scen] for g in G) + w['fc'] >= R_up[t], f\"Up_Reserve_{t}_{scen}\"\n",
        "        model += pl.lpSum(p_gen[g,t,scen] - Pmin[g]*u[g,t,scen] for g in G) >= R_down[t], f\"Down_Reserve_{t}_{scen}\"\n",
        "        # Ramp constraints (for t>0)\n",
        "        if t != T[0]:\n",
        "            for g in G:\n",
        "                model += p_gen[g,t,scen] - p_gen[g,T[0],scen] <= (RU[g] + y[g]*delta_RU[g])*dt, f\"Ramp_Up_{g}_{t}_{scen}\"\n",
        "                model += p_gen[g,T[0],scen] - p_gen[g,t,scen] <= (RU[g] + y[g]*delta_RU[g])*dt, f\"Ramp_Down_{g}_{t}_{scen}\" # symmetric\n",
        "        # Storage & Hydrogen limits\n",
        "        for s in S:\n",
        "            model += p_ch[s,t,scen] <= z[s]/dt, f\"Storage_Charge_Limit_{s}_{t}_{scen}\"\n",
        "            model += p_dis[s,t,scen] <= z[s]/dt, f\"Storage_Discharge_Limit_{s}_{t}_{scen}\"\n",
        "            model += soc[s,t,scen] <= z[s], f\"SOC_Capacity_Limit_{s}_{t}_{scen}\"\n",
        "        model += p_el_in[t,scen] <= w['el'], f\"Electrolyzer_Input_Limit_{t}_{scen}\"\n",
        "        model += p_fc_out[t,scen] <= w['fc'], f\"FuelCell_Output_Limit_{t}_{scen}\"\n",
        "        model += H2_sto[t,scen] <= w['store'], f\"H2_Storage_Capacity_Limit_{t}_{scen}\"\n",
        "    # Storage dynamics (simplified, assuming t1 and t0)\n",
        "    for s in S:\n",
        "        model += soc[s,T[1],scen] == soc[s,T[0],scen] + eta_ch[s]*p_ch[s,T[1],scen]*dt - (p_dis[s,T[1],scen]/eta_dis[s])*dt, f\"SOC_Dynamics_{s}_{scen}\"\n",
        "        model += soc[s,T[0],scen] == 0.5*z[s], f\"Initial_SOC_{s}_{scen}\"  # initial SOC\n",
        "    # Hydrogen balance\n",
        "    model += H2_sto[T[1],scen] == H2_sto[T[0],scen] + eta_el*p_el_in[T[1],scen]*dt - (p_fc_out[T[1],scen]/eta_fc)*dt, f\"H2_Dynamics_{scen}\"\n",
        "    model += H2_sto[T[0],scen] == 0.2*w['store'], f\"Initial_H2_Storage_{scen}\"\n",
        "\n",
        "# Solve\n",
        "model.solve(pl.PULP_CBC_CMD(msg=True))\n",
        "print(f\"Status: {pl.LpStatus[model.status]}\")\n",
        "print(f\"Total cost = {pl.value(model.objective):.2f} k$\")\n",
        "print(\"\\n--- Investment Decisions ---\")\n",
        "for g in G:\n",
        "    print(f\"Rehab {g}: {pl.value(y[g])}\")\n",
        "for s in S:\n",
        "    print(f\"Storage {s} Capacity: {pl.value(z[s]):.2f} MWh\")\n",
        "for h in H:\n",
        "    print(f\"Hydrogen {h} Capacity: {pl.value(w[h]):.2f} units\")\n",
        "\n",
        "print(\"\\n--- Operational Decisions (per scenario and time step) ---\")\n",
        "for scen in scenarios:\n",
        "    print(f\"\\nScenario: {scen}\")\n",
        "    for t in T:\n",
        "        print(f\"  Time Step: {t}\")\n",
        "        for g in G:\n",
        "            print(f\"    Generation {g}: {pl.value(p_gen[g,t,scen]):.2f} MW (Committed: {pl.value(u[g,t,scen])})\")\n",
        "        for s in S:\n",
        "            print(f\"    Storage {s} Charge: {pl.value(p_ch[s,t,scen]):.2f} MW, Discharge: {pl.value(p_dis[s,t,scen]):.2f} MW, SOC: {pl.value(soc[s,t,scen]):.2f} MWh\")\n",
        "        print(f\"    Electrolyzer Input: {pl.value(p_el_in[t,scen]):.2f} MW, Fuel Cell Output: {pl.value(p_fc_out[t,scen]):.2f} MW\")\n",
        "        print(f\"    H2 Storage Level: {pl.value(H2_sto[t,scen]):.2f} MWh\")\n",
        "        print(f\"    Load Shedding: {pl.value(LS[t,scen]):.2f} MW, Wind Curtailment: {pl.value(CW[t,scen]):.2f} MW, Solar Curtailment: {pl.value(CS[t,scen]):.2f} MW\")\n",
        "\n",
        "print(\"\\n--- Operational Costs per Scenario ---\")\n",
        "for scen in scenarios:\n",
        "    scenario_op_cost = pl.lpSum(C_var[g]*p_gen[g,t,scen] for g in G for t in T) + \\\n",
        "                       pl.lpSum(0.5*(p_ch[s,t,scen]+p_dis[s,t,scen]) for s in S for t in T) + \\\n",
        "                       pl.lpSum(0.1*(p_el_in[t,scen]+p_fc_out[t,scen]) for t in T) + \\\n",
        "                       pl.lpSum(VOLL*LS[t,scen] for t in T)\n",
        "    print(f\"Scenario {scen} Operational Cost: {pl.value(scenario_op_cost):.2f} k$\")"
      ]
    }
  ]
}