# -*- coding: utf-8 -*-
"""rep-flex-mpc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17iEy94aHR1W5ubaGrUxlpIwiZJghadjX
"""

!apt-get install -y -qq coinor-cbc

import pyomo.environ as pyo

def build_mpc_repowering():
    # ========== Sets ==========
    G = list(range(1, 11))        # 10 thermal units
    T = list(range(1, 13))        # 12 time steps
    S = list(range(1, 4))         # 3 storage units

    # ========== Fixed parameters ==========
    DeltaT = 5.0
    # Original unit data
    C_inc = {g: 10 + g for g in G}         # fuel cost [k$/MW]
    Pmin  = {g: 20 for g in G}
    Pmax_orig  = {g: 100 for g in G}        # original max capacity
    tau_orig   = {g: 10 for g in G}         # original time constant
    RU_orig = {g: Pmax_orig[g] / tau_orig[g] for g in G}   # MW/min
    RD_orig = {g: Pmax_orig[g] / tau_orig[g] for g in G}

    # Investment costs (much cheaper than slack penalty 1e4)
    Cost_inv_RU = {g: 50 for g in G}     # k$ per MW/min increase
    Cost_inv_Pmax = {g: 10 for g in G}   # k$ per MW increase

    # Maximum allowed upgrades (to keep it realistic)
    Max_Delta_RU = {g: 5.0 for g in G}    # can add up to 5 MW/min
    Max_Delta_Pmax = {g: 50 for g in G}  # can add up to 50 MW

    # Demand & reserves
    import math
    D = {t: 800 + 20 * math.sin(t * 0.5) for t in T}
    R_up_req   = {t: 50 for t in T}
    R_down_req = {t: 50 for t in T}

    # Initial conditions (still start at Pmin)
    p0    = {g: Pmin[g] for g in G}
    pbar0_orig = {g: Pmax_orig[g] for g in G}

    # Storage data
    eta_ch    = {1: 0.95, 2: 0.93, 3: 0.95}
    eta_dis   = {1: 0.95, 2: 0.93, 3: 0.95}
    E_max     = {1: 200, 2: 150, 3: 200}
    P_ch_max  = {1: 50, 2: 40, 3: 50}
    P_dis_max = {1: 50, 2: 40, 3: 50}
    SOC0      = {1: 100, 2: 75, 3: 100}

    M_penalty = 1e4

    # ========== Model ==========
    m = pyo.ConcreteModel("MPC_Repowering")
    m.G = pyo.Set(initialize=G)
    m.T = pyo.Set(initialize=T, ordered=True)
    m.S = pyo.Set(initialize=S)

    # --- Investment variables (endogenous) ---
    m.delta_RU = pyo.Var(m.G, domain=pyo.NonNegativeReals, bounds=lambda m,g: (0, Max_Delta_RU[g]))
    m.delta_Pmax = pyo.Var(m.G, domain=pyo.NonNegativeReals, bounds=lambda m,g: (0, Max_Delta_Pmax[g]))

    # Upgraded parameters (functions that return expressions involving investment variables)
    def RU_upgr(m, g):
        return RU_orig[g] + m.delta_RU[g]
    def RD_upgr(m, g):
        return RD_orig[g] + m.delta_RU[g]  # assume upgrade improves both equally
    def Pmax_upgr(m, g):
        return Pmax_orig[g] + m.delta_Pmax[g]
    # Initial available capacity might also increase if Pmax increases (conservatively assume pbar0 = Pmax_upgr)
    def pbar0_upgr(m, g):
        return Pmax_upgr(m, g)

    # --- Operational variables ---
    # Pyomo Var bounds must be constant or non-potentially variable expressions.
    # Since Pmax_upgr/RU_upgr functions return expressions involving other Pyomo Vars,
    # we define generous constant bounds here and enforce the actual variable bounds with constraints.

    # Define constant max possible values for bounds to use in Var declaration
    Max_P_overall = max(Pmax_orig.values()) + max(Max_Delta_Pmax.values())
    Max_RU_overall = max(RU_orig.values()) + max(Max_Delta_RU.values())

    m.p = pyo.Var(m.G, m.T, domain=pyo.NonNegativeReals, bounds=lambda m,g,t: (Pmin[g], Max_P_overall))
    m.pbar = pyo.Var(m.G, m.T, domain=pyo.NonNegativeReals, bounds=lambda m,g,t: (Pmin[g], Max_P_overall))
    m.x = pyo.Var(m.G, m.T, domain=pyo.NonNegativeReals, bounds=lambda m,g,t: (Pmin[g], Max_P_overall))
    # f can be negative, so bounds are (-Max_RU_overall, Max_RU_overall)
    m.f = pyo.Var(m.G, m.T, domain=pyo.Reals, bounds=lambda m,g,t: (-Max_RU_overall, Max_RU_overall))
    m.rup = pyo.Var(m.G, m.T, domain=pyo.NonNegativeReals, bounds=lambda m,g,t: (0, Max_RU_overall * DeltaT))
    m.rdown = pyo.Var(m.G, m.T, domain=pyo.NonNegativeReals, bounds=lambda m,g,t: (0, Max_RU_overall * DeltaT))

    # Storage variables (same as before)
    m.pch = pyo.Var(m.S, m.T, domain=pyo.NonNegativeReals, bounds=lambda m,s,t: (0, P_ch_max[s]))
    m.pdis = pyo.Var(m.S, m.T, domain=pyo.NonNegativeReals, bounds=lambda m,s,t: (0, P_dis_max[s]))
    m.SOC = pyo.Var(m.S, m.T, domain=pyo.NonNegativeReals, bounds=lambda m,s,t: (0, E_max[s]))
    m.y = pyo.Var(m.S, m.T, domain=pyo.Binary)

    pse_lb = {t: -sum(P_ch_max[s] for s in S) for t in T}
    pse_ub = {t:  sum(P_dis_max[s] for s in S) for t in T}
    m.pse = pyo.Var(m.T, domain=pyo.Reals, bounds=lambda m,t: (pse_lb[t], pse_ub[t]))

    # Slacks (still present for safety, but should be zero after investment)
    m.slack_balance_pos = pyo.Var(m.T, domain=pyo.NonNegativeReals, initialize=0)
    m.slack_balance_neg = pyo.Var(m.T, domain=pyo.NonNegativeReals, initialize=0)
    m.slack_res_up   = pyo.Var(m.T, domain=pyo.NonNegativeReals, initialize=0)
    m.slack_res_down = pyo.Var(m.T, domain=pyo.NonNegativeReals, initialize=0)

    # --- Objective: fuel cost + investment cost + slack penalties ---
    def obj_rule(m):
        fuel_cost = sum(C_inc[g] * m.p[g,t] * DeltaT/60 for g in m.G for t in m.T)
        invest_cost = sum(Cost_inv_RU[g] * m.delta_RU[g] + Cost_inv_Pmax[g] * m.delta_Pmax[g] for g in m.G)
        penalty = M_penalty * sum(
            m.slack_balance_pos[t] + m.slack_balance_neg[t] +
            m.slack_res_up[t] + m.slack_res_down[t] for t in m.T)
        return fuel_cost + invest_cost + penalty
    m.cost = pyo.Objective(rule=obj_rule, sense=pyo.minimize)

    # --- Constraints (identical to previous, but with upgraded parameters) ---
    # Power balance (relaxed)
    def balance_rule(m, t):
        return (sum(m.p[g,t] for g in m.G) + m.pse[t]
                + m.slack_balance_pos[t] - m.slack_balance_neg[t] == D[t])
    m.Balance = pyo.Constraint(m.T, rule=balance_rule)

    # Storage net
    def storage_net_rule(m, t):
        return m.pse[t] == sum(m.pdis[s,t] - m.pch[s,t] for s in m.S)
    m.StorageNet = pyo.Constraint(m.T, rule=storage_net_rule)

    # SOC dynamics
    def soc_dyn_rule(m, s, t):
        if t == m.T.first():
            return m.SOC[s,t] == SOC0[s] + (eta_ch[s]*m.pch[s,t] - m.pdis[s,t]/eta_dis[s]) * DeltaT/60
        else:
            t_prev = m.T.prev(t)
            return m.SOC[s,t] == m.SOC[s,t_prev] + (eta_ch[s]*m.pch[s,t] - m.pdis[s,t]/eta_dis[s]) * DeltaT/60
    m.SOCdyn = pyo.Constraint(m.S, m.T, rule=soc_dyn_rule)

    # Headroom dynamics with upgraded pbar0
    def head_dyn_rule(m, g, t):
        if t == m.T.first():
            return m.pbar[g,t] == pbar0_upgr(m,g) + (DeltaT/tau_orig[g]) * (m.x[g,t] - pbar0_upgr(m,g))
        else:
            t_prev = m.T.prev(t)
            return m.pbar[g,t] == m.pbar[g,t_prev] + (DeltaT/tau_orig[g]) * (m.x[g,t] - m.pbar[g,t_prev])
    m.HeadDyn = pyo.Constraint(m.G, m.T, rule=head_dyn_rule)

    # f definition
    def f_def_rule(m, g, t):
        if t == m.T.first():
            return m.f[g,t] == (m.pbar[g,t] - pbar0_upgr(m,g)) / DeltaT
        else:
            t_prev = m.T.prev(t)
            return m.f[g,t] == (m.pbar[g,t] - m.pbar[g,t_prev]) / DeltaT
    m.Fdef = pyo.Constraint(m.G, m.T, rule=f_def_rule)

    # Add constraints to enforce the actual (variable) Pmax/RU bounds
    def p_upper_bound_constraint_rule(m, g, t):
        return m.p[g,t] <= Pmax_upgr(m,g)
    m.PUpperBoundConstraint = pyo.Constraint(m.G, m.T, rule=p_upper_bound_constraint_rule)

    def pbar_upper_bound_constraint_rule(m, g, t):
        return m.pbar[g,t] <= Pmax_upgr(m,g)
    m.PbarUpperBoundConstraint = pyo.Constraint(m.G, m.T, rule=pbar_upper_bound_constraint_rule)

    def x_upper_bound_constraint_rule(m, g, t):
        return m.x[g,t] <= Pmax_upgr(m,g)
    m.XUpperBoundConstraint = pyo.Constraint(m.G, m.T, rule=x_upper_bound_constraint_rule)

    def f_upper_bound_constraint_rule(m, g, t):
        return m.f[g,t] <= RU_upgr(m,g)
    m.FUpperBoundConstraint = pyo.Constraint(m.G, m.T, rule=f_upper_bound_constraint_rule)

    def f_lower_bound_constraint_rule(m, g, t):
        return m.f[g,t] >= -RU_upgr(m,g)
    m.FLowerBoundConstraint = pyo.Constraint(m.G, m.T, rule=f_lower_bound_constraint_rule)

    def rup_upper_bound_constraint_rule(m, g, t):
        return m.rup[g,t] <= RU_upgr(m,g) * DeltaT
    m.RupUpperBoundConstraint = pyo.Constraint(m.G, m.T, rule=rup_upper_bound_constraint_rule)

    def rdown_upper_bound_constraint_rule(m, g, t):
        return m.rdown[g,t] <= RD_upgr(m,g) * DeltaT
    m.RdownUpperBoundConstraint = pyo.Constraint(m.G, m.T, rule=rdown_upper_bound_constraint_rule)

    # p <= pbar (This constraint was already there and remains valid)
    def p_bound_op_rule(m, g, t):
        return m.p[g,t] <= m.pbar[g,t]
    m.Pbound = pyo.Constraint(m.G, m.T, rule=p_bound_op_rule)

    # Ramp constraints (first step uses p0, subsequent steps use previous p)
    def ramp_up_rule(m, g, t):
        if t == m.T.first():
            return m.p[g,t] - p0[g] <= m.rup[g,t]
        else:
            t_prev = m.T.prev(t)
            return m.p[g,t] - m.p[g,t_prev] <= m.rup[g,t]
    m.RampUp = pyo.Constraint(m.G, m.T, rule=ramp_up_rule)

    def ramp_down_rule(m, g, t):
        if t == m.T.first():
            return p0[g] - m.p[g,t] <= m.rdown[g,t]
        else:
            t_prev = m.T.prev(t)
            return m.p[g,t_prev] - m.p[g,t] <= m.rdown[g,t]
    m.RampDown = pyo.Constraint(m.G, m.T, rule=ramp_down_rule)

    # Ramp capability limits using upgraded RU/RD
    # These constraints already properly use RU_upgr/RD_upgr in the body of the constraint,
    # which is allowed. The issue was only in the Var declaration's 'bounds' argument.
    def rup_lim1_rule(m, g, t):
        return m.rup[g,t] <= m.pbar[g,t] - m.p[g,t]
    m.RupLim1 = pyo.Constraint(m.G, m.T, rule=rup_lim1_rule)

    def rup_lim2_rule(m, g, t):
        return m.rup[g,t] <= RU_upgr(m,g) * DeltaT # This is fine as it's a constraint, not a Var bound
    m.RupLim2 = pyo.Constraint(m.G, m.T, rule=rup_lim2_rule)

    def rdown_lim1_rule(m, g, t):
        return m.rdown[g,t] <= m.p[g,t] - Pmin[g]
    m.RdownLim1 = pyo.Constraint(m.G, m.T, rule=rdown_lim1_rule)

    def rdown_lim2_rule(m, g, t):
        return m.rdown[g,t] <= RD_upgr(m,g) * DeltaT # This is fine as it's a constraint, not a Var bound
    m.RdownLim2 = pyo.Constraint(m.G, m.T, rule=rdown_lim2_rule)

    # Relaxed reserve requirements
    def res_up_rule(m, t):
        return sum(m.rup[g,t] for g in m.G) + m.slack_res_up[t] >= R_up_req[t]
    m.ResUp = pyo.Constraint(m.T, rule=res_up_rule)

    def res_down_rule(m, t):
        return sum(m.rdown[g,t] for g in m.G) + m.slack_res_down[t] >= R_down_req[t]
    m.ResDown = pyo.Constraint(m.T, rule=res_down_rule)

    # Storage exclusive modes
    def ch_dis_mode1_rule(m, s, t):
        return m.pch[s,t] <= P_ch_max[s] * m.y[s,t]
    m.ChDisMode1 = pyo.Constraint(m.S, m.T, rule=ch_dis_mode1_rule)

    def ch_dis_mode2_rule(m, s, t):
        return m.pdis[s,t] <= P_dis_max[s] * (1 - m.y[s,t])
    m.ChDisMode2 = pyo.Constraint(m.S, m.T, rule=ch_dis_mode2_rule)

    return m

if __name__ == "__main__":
    model = build_mpc_repowering()
    solver = pyo.SolverFactory('cbc')
    results = solver.solve(model, tee=True)

    if results.solver.termination_condition == pyo.TerminationCondition.optimal:
        print(f"Optimal total cost: {pyo.value(model.cost):.2f} k$")
        print("\n--- Investment decisions ---")
        for g in model.G:
            dRU = pyo.value(model.delta_RU[g])
            dPmax = pyo.value(model.delta_Pmax[g])
            if dRU > 1e-4 or dPmax > 1e-4:
                print(f"Unit {g}: ΔRU = {dRU:.2f} MW/min, ΔPmax = {dPmax:.2f} MW")
        # Check slacks
        slacks = sum(pyo.value(model.slack_balance_pos[t]) + pyo.value(model.slack_balance_neg[t]) +
                     pyo.value(model.slack_res_up[t]) + pyo.value(model.slack_res_down[t]) for t in model.T)
        print(f"Total slack used: {slacks:.4f}")
    else:
        print("No optimal solution found.")